homepage: "https://github.com/themoretheless/video-kadr"
language: rust
primary_contact: "d.o.mezhov@gmail.com"
main_repo: "https://github.com/themoretheless/video-kadr.git"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined
architectures:
  - x86_64
